APT::FTPArchive::Release::Origin "adguard-tray";
APT::FTPArchive::Release::Label "adguard-tray";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "all amd64 arm64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "adguard-tray APT repository";
